# Configuration reveal-md pour AI Seminar
title: "AI Seminar for Automotive Experts"
theme: black
highlightTheme: monokai
separator: "^---$"
verticalSeparator: "^--$"
charset: utf-8
template: template.html

# Configuration Reveal.js
revealOptions:
  hash: true
  width: "100%"
  height: "100%"
  margin: 0.05
  minScale: 0.1
  maxScale: 1.0
  transition: slide
  transitionSpeed: fast